### ISSUE TITLE
Tentative Instructions for Windows

### ISSUE THREAD

**Issue by Varriount** [arnetheduck/nlvm#1]
I think I have some tentative instructions for using nlvm on Windows, should I write them up here, or add to the README, or what?

**Comment by arnetheduck** [comment]
That's great - a patch to README, in a separate section maybe? I won't be able to maintain them though, so if you can also help keep them up to date, that would be great.

**Comment by Hades32** [comment]
I'd love to see that! This project needs to get more momentum! Transpiling to C is really so 1970s...

**Comment by ghost** [comment]
@Hades32 nim is not transpiled to C (if you were serious with your message).

**Comment by Hades32** [comment]
@Yardanico and why is the documentation ( https://nim-lang.org/docs/backends.html ) say so and why are all these ".c" files lying in my workdir then? Or do you just not like the term "transpiling"?

**Comment by ghost** [comment]
@Hades32 term "transpiling". 
![image](https://user-images.githubusercontent.com/21169548/40269290-5633700e-5b85-11e8-9264-2064b4ee6f27.png)

**Comment by Hades32** [comment]
@Yardanico not sure what I'm supposed to do with that cut off screenshot... Nevertheless the term used, it has been shown in a few projects that using LLVM-IR as an intermediate language produces more efficient code than using C as an intermediate language. Therefore I hope for @arnetheduck 's success...

**Comment by arnetheduck** [comment]
hey @Varriount , did you ever get around to make nlvm fly on windows?

**Comment by arnetheduck** [comment]
seems not, happy to see a patch one fine day
