### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by juancarlospaco** [arnetheduck/nlvm#11]
Whats the recommended way to install it permanently on the system :grey_question: 
Would be nice to have a `make install` that copies or symlinks the compiler binary and add it to the path.
Should I copy it into Nims folder :grey_question: 
Maybe a few lines on the readme and something to install it permanently should be cool. 
:slightly_smiling_face:

**Comment by arnetheduck** [comment]
I'm not sure, I generally avoid system-wide installations, so I haven't really thought about a good way to do this. I just run it from where it's built.

the easy option is to use make-dist.sh to create a portable binary - you can then put it anywhere you like, including `$HOME/bin` or whatever else you have in your path.

**Comment by arnetheduck** [comment]
no response and no patch
