### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by alker0** [arnetheduck/nlvm#12]
Hi,

While making nlvm, I receive the error and Ninja stop building.

System: Linux Mint 19.1 Tessa(x86_64)

gcc version: 7.4.0

nlvm commit: eff1603c

```
$ git clone git clone https://github.com/arnetheduck/nlvm.git
$ cd nlvm
$ git submodule update --init
$ sudo apt-get install libpcre3-dev libssl-dev libsqlite3-dev
$ make
```

After that, I repeat make command,

it progresses little by little while keeping stopping with the error just like before.

However in the final build step, it fails to build.

```
$ make compare
```

<details><summary>CMakeError.Log</summary>
Determining if the include file malloc/malloc.h exists failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_f9d92"
[1/2] Building C object CMakeFiles/cmTC_f9d92.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_f9d92.dir/CheckIncludeFile.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_f9d92.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: malloc/malloc.h: No such file or directory
 #include <malloc/malloc.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Determining if the include file valgrind/valgrind.h exists failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_2b846"
[1/2] Building C object CMakeFiles/cmTC_2b846.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_2b846.dir/CheckIncludeFile.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_2b846.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: valgrind/valgrind.h: No such file or directory
 #include <valgrind/valgrind.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Determining if the include file mach/mach.h exists failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_f4f45"
[1/2] Building C object CMakeFiles/cmTC_f4f45.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_f4f45.dir/CheckIncludeFile.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_f4f45.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: mach/mach.h: No such file or directory
 #include <mach/mach.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Determining if the include file histedit.h exists failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_0a10a"
[1/2] Building C object CMakeFiles/cmTC_0a10a.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_0a10a.dir/CheckIncludeFile.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_0a10a.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: histedit.h: No such file or directory
 #include <histedit.h>
          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Determining if the include file CrashReporterClient.h exists failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_96adb"
[1/2] Building C object CMakeFiles/cmTC_96adb.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_96adb.dir/CheckIncludeFile.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_96adb.dir/CheckIncludeFile.c.o   -c CheckIncludeFile.c
CheckIncludeFile.c:1:10: fatal error: CrashReporterClient.h: No such file or directory
 #include <CrashReporterClient.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Determining if the function pfm_initialize exists in the pfm failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_79d15"
[1/2] Building C object CMakeFiles/cmTC_79d15.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_79d15
FAILED: cmTC_79d15 
: && /usr/bin/cc -DCHECK_FUNCTION_EXISTS=pfm_initialize   CMakeFiles/cmTC_79d15.dir/CheckFunctionExists.c.o  -o cmTC_79d15  -lpfm -lm && :
ld: error: unable to find library -lpfm
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Determining if the pthread_create exist failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_8a42c"
[1/2] Building C object CMakeFiles/cmTC_8a42c.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_8a42c
FAILED: cmTC_8a42c 
: && /usr/bin/cc    CMakeFiles/cmTC_8a42c.dir/CheckSymbolExists.c.o  -o cmTC_8a42c  -lm && :
ld: error: undefined symbol: pthread_create
>>> referenced by CheckSymbolExists.c
>>>               CMakeFiles/cmTC_8a42c.dir/CheckSymbolExists.c.o:(main)
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_8c47b"
[1/2] Building C object CMakeFiles/cmTC_8c47b.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_8c47b
FAILED: cmTC_8c47b 
: && /usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create   CMakeFiles/cmTC_8c47b.dir/CheckFunctionExists.c.o  -o cmTC_8c47b  -lpthreads -lm && :
ld: error: unable to find library -lpthreads
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Determining if the function setupterm exists in the terminfo failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_184da"
[1/2] Building C object CMakeFiles/cmTC_184da.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_184da
FAILED: cmTC_184da 
: && /usr/bin/cc -DCHECK_FUNCTION_EXISTS=setupterm   CMakeFiles/cmTC_184da.dir/CheckFunctionExists.c.o  -o cmTC_184da  -lterminfo -lm && :
ld: error: unable to find library -lterminfo
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Determining if the function xar_open exists in the xar failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_e5be5"
[1/2] Building C object CMakeFiles/cmTC_e5be5.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_e5be5
FAILED: cmTC_e5be5 
: && /usr/bin/cc -DCHECK_FUNCTION_EXISTS=xar_open   CMakeFiles/cmTC_e5be5.dir/CheckFunctionExists.c.o  -o cmTC_e5be5  -lxar -lm && :
ld: error: unable to find library -lxar
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Determining if the arc4random exist failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_a262a"
[1/2] Building C object CMakeFiles/cmTC_a262a.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_a262a.dir/CheckSymbolExists.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_a262a.dir/CheckSymbolExists.c.o   -c CheckSymbolExists.c
CheckSymbolExists.c: In function ‘main’:
CheckSymbolExists.c:8:19: error: ‘arc4random’ undeclared (first use in this function); did you mean ‘srandom’?
   return ((int*)(&arc4random))[argc];
                   ^~~~~~~~~~
                   srandom
CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.

File /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdlib.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef arc4random
  return ((int*)(&arc4random))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Performing C SOURCE FILE Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_0007c"
[1/2] Building C object CMakeFiles/cmTC_0007c.dir/src.c.o
FAILED: CMakeFiles/cmTC_0007c.dir/src.c.o 
/usr/bin/cc   -DC_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW   -Werror=unguarded-availability-new -o CMakeFiles/cmTC_0007c.dir/src.c.o   -c src.c
cc1: error: -Werror=unguarded-availability-new: no option -Wunguarded-availability-new
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Determining if the mallctl exist failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_7a390"
[1/2] Building C object CMakeFiles/cmTC_7a390.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_7a390.dir/CheckSymbolExists.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_7a390.dir/CheckSymbolExists.c.o   -c CheckSymbolExists.c
CheckSymbolExists.c:2:10: fatal error: malloc_np.h: No such file or directory
 #include <malloc_np.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

File /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <malloc_np.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef mallctl
  return ((int*)(&mallctl))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the malloc_zone_statistics exist failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_421c7"
[1/2] Building C object CMakeFiles/cmTC_421c7.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_421c7.dir/CheckSymbolExists.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_421c7.dir/CheckSymbolExists.c.o   -c CheckSymbolExists.c
CheckSymbolExists.c:2:10: fatal error: malloc/malloc.h: No such file or directory
 #include <malloc/malloc.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

File /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <malloc/malloc.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef malloc_zone_statistics
  return ((int*)(&malloc_zone_statistics))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the strerror_s exist failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_a16fe"
[1/2] Building C object CMakeFiles/cmTC_a16fe.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_a16fe.dir/CheckSymbolExists.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_a16fe.dir/CheckSymbolExists.c.o   -c CheckSymbolExists.c
CheckSymbolExists.c: In function ‘main’:
CheckSymbolExists.c:8:19: error: ‘strerror_s’ undeclared (first use in this function); did you mean ‘strerror_l’?
   return ((int*)(&strerror_s))[argc];
                   ^~~~~~~~~~
                   strerror_l
CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.

File /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <string.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef strerror_s
  return ((int*)(&strerror_s))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the dladdr exist failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_463a9"
[1/2] Building C object CMakeFiles/cmTC_463a9.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_463a9.dir/CheckSymbolExists.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_463a9.dir/CheckSymbolExists.c.o   -c CheckSymbolExists.c
CheckSymbolExists.c: In function ‘main’:
CheckSymbolExists.c:8:19: error: ‘dladdr’ undeclared (first use in this function)
   return ((int*)(&dladdr))[argc];
                   ^~~~~~
CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.

File /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <dlfcn.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef dladdr
  return ((int*)(&dladdr))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Performing C SOURCE FILE Test HAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_b2595"
[1/2] Building C object CMakeFiles/cmTC_b2595.dir/src.c.o
FAILED: CMakeFiles/cmTC_b2595.dir/src.c.o 
/usr/bin/cc   -DHAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC -o CMakeFiles/cmTC_b2595.dir/src.c.o   -c src.c
src.c: In function ‘main’:
src.c:7:37: error: ‘struct stat’ has no member named ‘st_mtimespec’; did you mean ‘st_mtim’?
    (void)sizeof(((struct stat *)0)->st_mtimespec.tv_nsec);
                                     ^~~~~~~~~~~~
                                     st_mtim
ninja: build stopped: subcommand failed.

Source file was:

#include <sys/types.h>
#include <sys/stat.h>

int main()
{
   (void)sizeof(((struct stat *)0)->st_mtimespec.tv_nsec);
   return 0;
}

Performing C++ SOURCE FILE Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_2f6e9"
[1/2] Building CXX object CMakeFiles/cmTC_2f6e9.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_2f6e9.dir/src.cxx.o 
/usr/bin/c++    -DSUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG   -Wgnu-zero-variadic-macro-arguments -o CMakeFiles/cmTC_2f6e9.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-Wgnu-zero-variadic-macro-arguments'; did you mean '-Wno-variadic-macros'?
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_5d550"
[1/2] Building CXX object CMakeFiles/cmTC_5d550.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_5d550.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -DCXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW   -Werror -Werror=unguarded-availability-new -o CMakeFiles/cmTC_5d550.dir/src.cxx.o -c src.cxx
cc1plus: error: -Werror=unguarded-availability-new: no option -Wunguarded-availability-new
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_22d0e"
[1/2] Building C object CMakeFiles/cmTC_22d0e.dir/src.c.o
FAILED: CMakeFiles/cmTC_22d0e.dir/src.c.o 
/usr/bin/cc   -fPIC -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -DC_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG   -Werror -Wcovered-switch-default -o CMakeFiles/cmTC_22d0e.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wcovered-switch-default'; did you mean '-Wno-switch-default'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_f5ec8"
[1/2] Building CXX object CMakeFiles/cmTC_f5ec8.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_f5ec8.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -DCXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG   -Werror -Wcovered-switch-default -o CMakeFiles/cmTC_f5ec8.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-Wcovered-switch-default'; did you mean '-Wno-switch-default'?
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_0b0c2"
[1/2] Building CXX object CMakeFiles/cmTC_0b0c2.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_0b0c2.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -DCXX_SUPPORTS_CLASS_MEMACCESS_FLAG   -Wclass-memaccess -o CMakeFiles/cmTC_0b0c2.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-Wclass-memaccess'
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_37588"
[1/2] Building C object CMakeFiles/cmTC_37588.dir/src.c.o
FAILED: CMakeFiles/cmTC_37588.dir/src.c.o 
/usr/bin/cc   -fPIC -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -DC_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG   -Werror -Wdelete-non-virtual-dtor -o CMakeFiles/cmTC_37588.dir/src.c.o   -c src.c
cc1: error: command line option '-Wdelete-non-virtual-dtor' is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C SOURCE FILE Test C_WCOMMENT_ALLOWS_LINE_WRAP failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_415f2"
[1/2] Building C object CMakeFiles/cmTC_415f2.dir/src.c.o
FAILED: CMakeFiles/cmTC_415f2.dir/src.c.o 
/usr/bin/cc -D_GNU_SOURCE  -fPIC -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -DC_WCOMMENT_ALLOWS_LINE_WRAP  -Werror -Wcomment -o CMakeFiles/cmTC_415f2.dir/src.c.o   -c src.c
src.c:1:1: error: multi-line comment [-Werror=comment]
 // \
 ^
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

Source file was:
// \
//
int main() {return 0;}
Performing C SOURCE FILE Test C_SUPPORTS_STRING_CONVERSION_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_a5ba2"
[1/2] Building C object CMakeFiles/cmTC_a5ba2.dir/src.c.o
FAILED: CMakeFiles/cmTC_a5ba2.dir/src.c.o 
/usr/bin/cc   -fPIC -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-comment -DC_SUPPORTS_STRING_CONVERSION_FLAG   -Werror -Wstring-conversion -o CMakeFiles/cmTC_a5ba2.dir/src.c.o   -c src.c
cc: error: unrecognized command line option '-Wstring-conversion'; did you mean '-Wint-conversion'?
ninja: build stopped: subcommand failed.

Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test CXX_SUPPORTS_STRING_CONVERSION_FLAG failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_fe714"
[1/2] Building CXX object CMakeFiles/cmTC_fe714.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_fe714.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -DCXX_SUPPORTS_STRING_CONVERSION_FLAG   -Werror -Wstring-conversion -o CMakeFiles/cmTC_fe714.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-Wstring-conversion'; did you mean '-Wint-conversion'?
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test LINKER_SUPPORTS_COLOR_DIAGNOSTICS failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_5c625"
[1/2] Building CXX object CMakeFiles/cmTC_5c625.dir/src.cxx.o
[2/2] Linking CXX executable cmTC_5c625
FAILED: cmTC_5c625 
: && /usr/bin/c++  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -DLINKER_SUPPORTS_COLOR_DIAGNOSTICS  -fuse-ld=gold -Wl,--color-diagnostics CMakeFiles/cmTC_5c625.dir/src.cxx.o  -o cmTC_5c625  -lm && :
/usr/bin/ld.gold: --color-diagnostics: unknown option
/usr/bin/ld.gold: use the --help option for usage information
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_6988b"
[1/2] Building CXX object CMakeFiles/cmTC_6988b.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_6988b.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors -DHAVE_CXX_FLAG_WSHORTEN_64_TO_32  -Wshorten-64-to-32   -Wshorten-64-to-32 -o CMakeFiles/cmTC_6988b.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-Wshorten-64-to-32'
c++: error: unrecognized command line option '-Wshorten-64-to-32'
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WD654 failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_8de3b"
[1/2] Building CXX object CMakeFiles/cmTC_8de3b.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_8de3b.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exceptions  -Wstrict-aliasing -DHAVE_CXX_FLAG_WD654  -wd654   -wd654 -o CMakeFiles/cmTC_8de3b.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-wd654'
c++: error: unrecognized command line option '-wd654'
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WTHREAD_SAFETY failed with the following output:
Change Dir: /opt/nlvm/ext/llvm-8.0.0.src/sha/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_d1c09"
[1/2] Building CXX object CMakeFiles/cmTC_d1c09.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_d1c09.dir/src.cxx.o 
/usr/bin/c++    -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exceptions  -Wstrict-aliasing -DHAVE_CXX_FLAG_WTHREAD_SAFETY  -Wthread-safety   -Wthread-safety -o CMakeFiles/cmTC_d1c09.dir/src.cxx.o -c src.cxx
c++: error: unrecognized command line option '-Wthread-safety'; did you mean '-fthread-jumps'?
c++: error: unrecognized command line option '-Wthread-safety'; did you mean '-fthread-jumps'?
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
</details>

<details><summary>End_of_Make.txt</summary>
<code>
cd Nim ;\
[ -d csources ] || git clone --depth 1 https://github.com/nim-lang/csources.git ;\
cd csources ;\
git pull ;\
sh build.sh
Already up to date.
# OS: linux
# CPU: amd64
cd Nim ; bin/nim c koch
Makefile:33: recipe for target 'Nim/koch' failed
</code>
</details>

**Comment by arnetheduck** [comment]
it looks like you don't have a working C compiler installed, or something else is wrong with your build environment (for example `CC`/`CXX` env var set to something unsupported. 

You're unable to build `llvm` (which is a prerequisite of `nlvm` so I suggest you start there: http://clang.llvm.org/get_started.html
