### ISSUE TITLE
Wasm32: memcpy import

### ISSUE THREAD

**Issue by jacqueswww** [arnetheduck/nlvm#15]
When compiling a king_of_the_hill.nim example in https://github.com/status-im/nimplay/tree/af68eb68482c4114fb507dd41cd3d2c9bf3f670e
`memcpy` will imported, which is undesired (memcpy should be included in the file).
```
$ wasm2wat examples/king_of_the_hill.wasm | grep memcpy
  (import "env" "memcpy" (func (;3;) (type 2)))
```
Which the equivalent clang + nim does not do, I suspect this is related to the clang flag `-nostdlib` which I am unable to set with _nlvm_.

The nim + clang compiler uses the following options:
```
--os:standalone
--cpu:i386
--cc:clang
--gc:none
--nomain
--target=wasm32-unknown-unknown-wasm
--clang.options.linker:"-nostdlib -Wl,--no-entry,--allow-undefined,--strip-all"
```
NLVM uses:
```
-d:release 
--nlvm.target=wasm32 
--gc:none
 -l:--compress-relocations
 -l:--no-entry
 -l:--allow-undefined
 -l:--strip-all
 --noMain
```

**Comment by arnetheduck** [comment]
looked a bit and it's not that simple - it may be that we need to provide memset/memcpy for now - ie even clang-8 will produce calls to this function:

`test.c`:
```c
int main(int a, char** b) {
	int x[100] = {};
	
	return x[2];
}
```

`clang --target=wasm32-unknown-unknown -nostdlib -S test.c` `test.s`:
```
...
	local.get	5
	local.get	8
	local.get	7
	i32.call	memset@FUNCTION
	drop
	local.get	4
	i32.load	8
...
```

bulk mem issues being considered:

https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md

https://reviews.llvm.org/rGbba3f06d05e33ff113e17f85c34aa87c94d619e7

**Comment by jacqueswww** [comment]
Interesting, will definitely dig some more. The memset direct wasm replacement option seem like the way to go then. But I find it interesting that nim + clang doesn't use the external memset but NLVM does?

**Comment by arnetheduck** [comment]
for now, I would try to just reimplement them in any way possible (ie with a loop one byte at a time) - one easy way is to add them to https://github.com/arnetheduck/nlvm/blob/master/nlvm-lib/nlvmbase-wasm32-Standalone.ll (see corresponding file for amd64 in same folder for similar examples) which nlvm will pick up while compiling.

I suspect `llvm-9` changes all this so whatever fix we add now might be obsolete soon since it's just around the corner - would make sense to reassess after that.

**Comment by arnetheduck** [comment]
updated to llvm-9 but the problem remains, so this will need an impl in nlvmbase

**Comment by arnetheduck** [comment]
https://gcc.godbolt.org/z/4uAyeo

**Comment by arnetheduck** [comment]
In clang this needs a flag: https://stackoverflow.com/questions/67068195/does-clang-provide-intrinsics-for-webassemblys-memory-fill-and-memory-copy/67084011#67084011 (`-mbulk-memory`). 

Other extensions, and where they're supported: https://webassembly.org/roadmap/

**Comment by arnetheduck** [comment]
documented in https://github.com/arnetheduck/nlvm/commit/5d04d529bad92479964e29f057468a0102cc9f69
