### ISSUE TITLE
Compatibility with Nim GC

### ISSUE THREAD

**Issue by Varriount** [arnetheduck/nlvm#2]
It currently appears that any code relying on Nim's GC fails, primarily due to broken references. Is there any way or are there any plans on how to fix this? I'd be willing to try my hand at fixing this, if given some direction.

**Comment by arnetheduck** [comment]
LLVM supports several garbage collected languages through http://llvm.org/releases/3.7.1/docs/GarbageCollection.html - I would start there and see how that can be integrated with nlvm. The other issue is that exception handling is not done yet, which in certain ways affects GC as well.

**Comment by Varriount** [comment]
The most recent LLVM documentation seems to recommend using [statepoints](http://llvm.org/releases/3.7.1/docs/Statepoints.html), however, I must admit that my grasp of what actually needs to be done is tenuous. The documentation seems to suggest marking function calls?

**Comment by Varriount** [comment]
@arnetheduck Another (temporary) alternative might be somehow interfacing with the [Boehm GC](http://hboehm.info/gc/)

**Comment by arnetheduck** [comment]
well, I'm not much ahead of you there, it's the first time I do an llvm compiler (and use Nim, for that matter), but what llvm offers is just compiler-generated hints.. those hints have to be taken by a gc, so I suspect some retrofitting of the existing gc's would be needed..

that said, many apps will run just fine without a GC as long as there's enough memory around, which there typically is for a lot of use cases, so a temporary solution might not be that useful. I also think that even for boehm, the compiler may be able to give it hints to make it more efficient,,

**Comment by arnetheduck** [comment]
fixed in 68140ae
