### ISSUE TITLE
cannot build on macos

### ISSUE THREAD

**Issue by bentxt** [arnetheduck/nlvm#27]
hi,
make fails with

CMake Error at cmake/modules/HandleLLVMOptions.cmake:273 (message):
  Host compiler does not support '-fuse-ld=gold'

I do have an working llvm installed (Homebrew) in /usr/local/Cellar/llvm/11.0.0/

Doesn't seems to be recognized, since the nlvm build script tries to build llvm from sources

**Comment by arnetheduck** [comment]
Per the README, osx is indeed not supported (I don't have/use a mac) - happy to take contributions
