### ISSUE TITLE
Sonthing questions about j2c

### ISSUE THREAD

**Issue by hzka** [arnetheduck/nlvm#5]
Hello,I am a student from NWU,i am interested in your j2c project,and i have a question about this:
     When i use translate to C++.the java project reverses c project successfully,And i compile this c project in linux Eclipse CDT successfully,It generates libname.a  and libext.a,but when i run it.it told me launch failed annd binary not found.i don't know why.where is .exe file.I only has .a File.how can i run it?I almost use all methods on Internet.could you tell me how to run it?thank you very much

**Comment by arnetheduck** [comment]
you can check out this tutorial to find out more about how the C/C++ toolchain works - knowing this is a prerequisite for using j2c: https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html

**Comment by hzka** [comment]
Thank you very much~,i am trying to solve this question.it told me:
Building file: ../src/testing/Hello-main.cpp
Invoking: GCC C++ Compiler
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/testing/Hello-main.d" -MT"src/testing/Hello-main.d" -o "src/testing/Hello-main.o" "../src/testing/Hello-main.cpp"
../src/testing/Hello-main.cpp:1:29: fatal error: testing/Hello.hpp: 没有那个文件或目录
 #include <testing/Hello.hpp>
                             ^
compilation terminated.
src/testing/subdir.mk:21: recipe for target 'src/testing/Hello-main.o' failed
make: *** [src/testing/Hello-main.o] Error 1

but exactly  i have this file,i don't know what happenend,maybe i need more time to solve it.

**Comment by arnetheduck** [comment]
seriously - you're posting in the wrong project without doing any background research. up your game before posting again.
