### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by lf-araujo** [arnetheduck/nlvm#64]
Hi, can you please help me identifying what I am missing to build this package?

make complains of:

```
.o c_code/1_2/@mmain.nim.o c_code/2_2/@mscriptconfig.nim.o c_code/2_2/@mcmdlinehelper.nim.o c_code/2_2/@mnim.nim.o -ldl -lm -lrt
SUCCESS
make[1]: Leaving directory '/home/luis/Documents/OneDrive/Coding/Nim/nlvm/Nim/csources_v1'
cd Nim ; bin/nim c koch
/home/luis/Documents/OneDrive/Coding/Nim/nlvm/Nim/config/nim.cfg(52, 1) Error: invalid package name: /home/luis/.nimble/pkgs2/x11-1.1-dad7b243bb290af47fcd9603340f428e5590bb5a
make: *** [Makefile:34: Nim/koch] Error 1
```

**Comment by arnetheduck** [comment]
removing your nimble folder entirely (`/home/luis/.nimble`) sounds like a good start - it is known to introduce many build problems in general.

**Comment by lf-araujo** [comment]
Will try this and report back in half an hour. Thank you.

**Comment by lf-araujo** [comment]
Yep, this worked.

**Comment by lf-araujo** [comment]
nlvm expects the shared libraries in certain folders. I wanted to install in my nimble/bin folder, which folders should I move over to /bin? There is no make install option, right?

Thank you.

**Comment by arnetheduck** [comment]
See instructions about compiling a static binary: https://github.com/arnetheduck/nlvm?tab=readme-ov-file#compile-instructions
